PE-381 Upgrade to PHP 8.1. Add PHPStan.
eGovPDX/employees pull request #389
Opened 2022-09-27 20:35 UTC by kxwang

2022-10-06 23:20 UTC, joshuami requested changes

2022-10-06 23:20 UTC, joshuami commented on phpstan.neon
> +
Needs a newline.

2022-10-06 23:30 UTC, kxwang commented on phpstan.neon
> +
New line added.

2022-10-06 23:58 UTC, joshuami submitted a review, later dismissed

2022-10-07 17:12 UTC, joshuami approved these changes

2022-10-07 20:58 UTC, merged