PE-16 Add westy build to lando config + ignore built assets
eGovPDX/employees pull request #409
Opened 2022-10-31 20:08 UTC by odensc

2022-11-01 17:47 UTC, joshuami approved these changes

2022-11-02 21:02 UTC, RichardDavies requested changes

2022-11-02 21:02 UTC, RichardDavies commented on .lando.yml
> +      - npm -C /app/web/themes/custom/westy run production
I think we should also run `npm install` and `npm run production` as part of `lando refresh` on line 129. (We do a similar theme rebuild in portlandor for `lando refresh`.)

2022-11-02 21:35 UTC, RichardDavies approved these changes

2022-11-02 21:35 UTC, merged