PE-40-3 trying to add group roles to join/leave link
eGovPDX/employees pull request #422
Opened 2022-12-09 01:10 UTC by ccdatapdx

2022-12-13 21:12 UTC, joshuami approved these changes

2022-12-14 17:41 UTC, odensc requested changes

2022-12-14 17:41 UTC, odensc commented on web/modules/custom/portland_groups/modules/group_views_join_link/src/Plugin/views/field/JoinLeaveLink.php
>        // Do not display join/leave link if the user has Employee or Assigned role
This comment should be updated to match the new roles array.

2022-12-14 17:41 UTC, odensc commented on web/sites/default/config/views.view.group_list_views.yml
> +            text: '{{group_join_leave_link}}'
This shouldn't be needed, it's not actually rewriting anything

2022-12-14 17:42 UTC, odensc approved these changes

2022-12-14 17:53 UTC, merged